spring:
  profiles:
    include: real
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:gcs-key.json
        project-id: delta-pagoda-398907
        bucket: dango-image

jwt:
  header: Authorization
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: hellothisismydangoplageserverjwtsecretkeyhellothisismydangoplageserverjwtsecretkeyhellothisismydangoplageserverjwtsecretkeyhellothisismydangoplageserverjwtsecretkeyhellothisismydangoplageserverjwtsecretkeyhellothisismydangoplageserverjwtsecretkey
  #token-validity-in-seconds: 86400
  refresh: hellothisismydangoplageserverjwtsecretkeyhellothisismydangoplageserverjwtsecretkeyhellothisismydangoplageserverjwtsecretkeyhellothisismydangoplageserverjwtsecretkeyhellothisismydangoplageserverjwtsecretkeyhellothisismydangoplageserverjwtsecretkey
  access-token-seconds: 604800 * 5
  refresh-token-seconds: 6000

kakao:
  client-id: b7efcdeef9cf0be8991e8d2fdc1dc2ba
  redirect-uri: http://35.216.0.111:8080/oauth/kakao
  #redirect-uri: dangoplate://oauth
  api-url: https://dapi.kakao.com
  rest-api-key: ${KAKAO_REST_API_KEY}