spring:
  profiles:
    include: real

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${db.url}
#    username: ${db.username}
#    password: ${db.password}
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  header: Authorization
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: hellothisismydangoplageserverjwtsecretkeyhellothisismydangoplageserverjwtsecretkey
  #token-validity-in-seconds: 86400
  refresh: hellothisismydangoplageserverjwtsecretkeyhellothisismydangoplageserverjwtsecretkey
  access-token-seconds: 600
  refresh-token-seconds: 6000

