name: Deploy to GCP Instance using SSH

on:
  push:
    branches: ['main']

env:
  PROJECT_ID: 'thermal-elixir-403003'
  GCE_INSTANCE: 'dango-plate'
  GCE_INSTANCE_ZONE: 'asia-northeast3-a'
  PROJECT_NAME: 'Dango-Plate-Backend-Reference'
  BRANCH: 'main'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/minskim3/${{ env.PROJECT_NAME }}

            git checkout ${{ env.BRANCH }}
            git fetch --all
            git reset --hard origin/${{ env.BRANCH }}
            git pull origin ${{ env.BRANCH }}

            if [ "$(docker ps -aq -f name=spring)" ]
            then
              echo "[ spring is running ]"
              echo "[ restart spring ]"
              docker restart spring
            else
              echo "[ spring is not running ]"
              echo "[ run spring ]"
              docker build -t dango-plate .
              docker run -d -p ${{ secrets.SPRING_PORT }}:${{ secrets.SPRING_PORT}} --name spring -v /home/minskim3/${{ env.PROJECT_NAME }}:/backend/${{env.PROJECT_NAME }} dango-plate
            fi
