name: Deploy to GCP Instance using SSH

on:
  push:
    branches: ['main']

env:
  PROJECT_ID: 'thermal-elixir-403003'
  GCE_INSTANCE: 'dango-plate'
  GCE_INSTANCE_ZONE: 'asia-northeast3-a'
  PROJECT_NAME: 'Dango-Plate-Backend-Reference'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/minskim3/${{ env.PROJECT_NAME }}

            git checkout main
            git fetch --all
            git reset --hard origin/main
            git pull origin main

            echo "DATASOURCE_URL=${{ secrets.DATASOURCE_URL }}" > .env
            echo "DATASOURCE_USERNAME=${{ secrets.DATASOURCE_USERNAME }}" >> .env
            echo "DATASOURCE_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }}" >> .env
            echo "KAKAO_REST_API_KEY=${{ secrets.KAKAO_REST_API_KEY }}" >> .env

            docker build -t dango-plate .
            
            if [ "$(docker ps -aq -f name=spring)" ]
            then
              echo "[ spring is running ]"
              echo "[ restart spring ]"
              docker rm spring  
            else
              echo "[ spring is not running ]"
              echo "[ run spring ]"
            fi
            
            docker run -d -p ${{ secrets.SPRING_PORT }}:${{ secrets.SPRING_PORT}} --env-file ./.env --name spring -v /home/minskim3/${{ env.PROJECT_NAME }}:/backend/${{env.PROJECT_NAME }} dango-plate